### ISSUE TITLE
无法通过maven/gradle使用该sdk

### ISSUE THREAD

**Issue by zxkane** [baidubce/bce-sdk-java#1]
release版本没有发布到公开的repo.maven或自己的host的repo？

在pom中添加bce-sdk-java依赖无法被解析。

**Comment by xuchuan** [comment]
http://mvnrepository.com/artifact/com.baidubce/bce-java-sdk
发布的名称是bce-java-sdk，不是bce-sdk-java。git库名和pom名字不一致导致了混淆，抱歉！
