### ISSUE TITLE
BccClient的Region问题

### ISSUE THREAD

**Issue by lynch0571** [baidubce/bce-sdk-java#11]
我使用了bce-java-sdk的0.10.144版本(目前最新)，无法通过BccClient查询到**非北京地域**的云主机。原因可能是new BccClient时需要配置BccClientConfiguration，而config.setRegion()**只能传Region.CN_N1这一个枚举值**，在Region中没有其他地域的枚举值。

``` java
BccClientConfiguration config = new BccClientConfiguration();
config.setRegion(Region.CN_N1);//源码只有CN_N1一个枚举值，对应"bj"，北京
config.setCredentials(new DefaultBceCredentials(ACCESS_KEY_ID, SECRET_ACCESS_KEY));
BccClient client = new BccClient(config);
```

请问通过java SDK能否查询非北京地域的云主机？how to get it?

**Comment by FriendshipBridge** [comment]
问题已过期
