### ISSUE TITLE
401错误

### ISSUE THREAD

**Issue by fishsoft** [baidubce/bce-sdk-java#2]
请求时提示BecResponseException{httpStatus='401', requestId='null', code='AuthError', message='Bad signature or AK string and SK string do not match.'}
header提交参数有：
header.put("accept", "/");
header.put("accept-encoding","gzip, deflate");
header.put("connection", "keep-alive");
header.put("content-Length", "8");
header.put("content-Type", "application/json");
header.put("x-bce-date", DateUtils.formatAlternateIso8601Date(new Date()));
签证使用的sdk的签证

**Comment by baichengzhou** [comment]
哎 我也遇到了，怎么搞都不好使，百度的API是最难用的。

**Comment by FriendshipBridge** [comment]
请更新最新版本。
